### ISSUE TITLE
TypeError: Cannot read property 'pushNotification' of undefined

### ISSUE THREAD

**Issue by phanthinh** [otelnov/pushNews#1]
@otelnov 

I'm saw this issue for source...

TypeError: Cannot read property 'pushNotification' of undefined
    at Object.register (http://domain.com/lib/ngCordova/dist/ng-cordova.js:5701:24)
    at http://domain.com/js/app.js:233:18
    at http://domain.com/lib/ionic/js/ionic.bundle.js:44815:19
    at Object.ionic.Platform.ready (http://domain.com/lib/ionic/js/ionic.bundle.js:2120:9)
    at Object.IonicModule.constant.provider.$get.self.ready (http://domain.com/lib/ionic/js/ionic.bundle.js:44813:26)
    at Scope.$scope.pushRegister (http://domain.com/js/app.js:213:18)
    at http://domain.com/js/app.js:207:14
    at processQueue (http://domain.com/lib/ionic/js/ionic.bundle.js:21888:27)
    at http://domain.com/lib/ionic/js/ionic.bundle.js:21904:27
    at Scope.$get.Scope.$eval (http://domain.com/lib/ionic/js/ionic.bundle.js:23100:28)

**Comment by filipecrosk** [comment]
Hi @phanthinh did you solved it? It only appears on the browser during your tests, right?
It worked for me on iPhone but still appears on my browser.
